services:
  traefik:
    build: ./traefik
    image: clinic-hub-traefik:v0.1.0
    ports:
      - "80:80"
    restart: always
    networks:
      - web

  keycloak:
    build: ./keycloak
    image: clinic-hub-keycloak:v0.1.0
    depends_on:
      - db
    restart: always
    networks:
      - web

  db:
    build: ./postgres
    image: clinic-hub-postgres:v0.1.0
    ports:
      - "5432:5432"
    restart: always
    networks:
      - web

  krakend:
    build: ./krakend
    image: clinic-hub-krakend:v0.1.0
    ports:
      - "8080:8080" # KrakenD Gateway
    restart: always
    networks:
      - web

networks:
  web:
    driver: bridge
